---
title: "PFAS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(plotly)
```

# PF*S: What Do We Know?


```{r read_data}
setwd <- "C:/Users/Leah/Documents/Datathon_PFAS/"
SAR_all <- read.csv("SAR_537Data_20190808_All.csv", header = T)
names(SAR_all) <- c("Station", "Parameter_FullName", "Param_abv", "Date", "Time", "ResultVal10_ND", 
                    "Result_txt", "Units", "RDL", "Detect_YN", "LabSampNum", "Method")
SAR_all$Result <- as.character(SAR_all$Result_txt)
SAR_all$Result[grepl("ND", SAR_all$Result)] <- 0.000001
SAR_all$Result <- as.numeric(SAR_all$Result)
SAR_all$Date <- as.Date(SAR_all$Date, "%m/%d/%Y")


```

## All PF* Compounds Over Time

```{r}
ggplotly(
   ggplot(SAR_all[grepl("^PF", SAR_all$Param_abv),]) +
        geom_line(aes(x=Date, y=Result, group = Param_abv, color = Param_abv)) +
        scale_colour_viridis_d("Parameter") +
        labs(#title = "Childs Meadow All Years",
             x = "Sample Date", y = "Concentration") +
        theme_bw()
    
#    , tooltip = "text")  
   ) %>% 
      rangeslider(start = min(as.numeric(SAR_all$Date)), 
                  end = max(as.numeric(SAR_all$Date)))
  
```



## PFOA and PFOS Over Time


```{r, echo=FALSE}
ggplotly(
   ggplot(SAR_all[grepl("^PFO", SAR_all$Param_abv),]) +
        geom_line(aes(x=Date, y=Result, group = Param_abv, color = Param_abv)) +
        scale_colour_viridis_d("Parameter",end = 0.7) +
        labs(#title = "Childs Meadow All Years",
             x = "Sample Date", y = "Concentration") +
        theme_bw()
    
#    , tooltip = "text")  
   ) %>% 
      rangeslider(start = min(as.numeric(SAR_all$Date)), 
                  end = max(as.numeric(SAR_all$Date)))
  
```

## PFOA By Year

```{r}
SAR_all$YYYY <- as.factor(lubridate::year(SAR_all$Date))
SAR_all$DOY <- lubridate::yday(SAR_all$Date)
SAR_PFOA <- filter(SAR_all, Param_abv == "PFOA")
ggplotly(
   ggplot(SAR_PFOA) +
        geom_line(aes(x=DOY, y=Result, group = as.factor(YYYY), color = YYYY)) +
        scale_colour_viridis_d("Year") +
        labs(#title = "Childs Meadow All Years",
             x = "Sample Date", y = "Concentration") +
        theme_bw()
    
#    , tooltip = "text")  
   ) %>% 
      rangeslider(start = 1, end = 365)
  
```

## PFOS By Year

```{r}
SAR_PFOS <- filter(SAR_all, Param_abv == "PFOS")
ggplotly(
   ggplot(SAR_PFOS) +
        geom_line(aes(x=DOY, y=Result, group = as.factor(YYYY), color = YYYY)) +
        scale_colour_viridis_d("Year") +
        labs(#title = "Childs Meadow All Years",
             x = "Sample Date", y = "Concentration") +
        theme_bw()
    
#    , tooltip = "text")  
   ) %>% 
      rangeslider(start = 1, end = 365)
  
```

